version: '3'

tasks:
  world:
    aliases: [ default ]
    cmds:
      - task: install
      - task: clean
     # - task: check
      - task: test
      - task: build

  run-local: ./run-local.sh

  install:
    cmd: npm ci
    sources:
      - package.json
      - package-lock.json
    status:
      - test -d node_modules


  clean: npm run clean
  check: npm run check
  test: npm run test
  build: npm run build
